services:
  api-proxy:
    build: .
    container_name: api-proxy
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
    environment:
      - ADMIN_PASSWORD=admin
    restart: always
